CREATE TABLE IF NOT EXISTS tenants (
    id UUID PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    schema_name VARCHAR(150) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE'
);
